### PR TITLE
Add usage examples to README

### PR DESCRIPTION
**Pull request by abeluck**
### Motivation

How do you use this collection? How do you use sops and ansible?

### Changes description
This PR adds documentation on how to use this collection.

### Additional notes
I included docs for the lookup and vars plugins as I presume the vars plugin will be merged to main shortly.

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by endorama** [comment]
@abeluck thanks for the PR! I would merge it after #6 is done to avoid confusion, but this is a much needed improvement.

**Comment by felixfontein** [comment]
@endorama since #6 is now merged, do you want to merge this now? Also, do you want to release a first version (0.1.0) of the collection now, or do some more work first?

**Comment by endorama** [comment]
@felixfontein Yes! Merging it now.

**Comment by endorama** [comment]
Thanks @abeluck!

**Pull request merged**
