### PR TITLE
vars and lookup plugins: fix syntax in Ansible vars specification so options can actually provided with vars

### PR DESCRIPTION
**Pull request by felixfontein**
I used the wrong syntax in #47.

### CODE REVIEW

**Review by endorama — APPROVED** [review]

**Comment by endorama** [comment]
@felixfontein does this qualify to trigger a release? (I guess so as the docs are wrong)

**Comment by felixfontein** [comment]
@endorama it does, though we can also wait a few days (say until the end of this week) to see whether other reviewers find something else.

**Comment by endorama** [comment]
Sounds good, meanwhile merging this one.

**Comment by felixfontein** [comment]
@endorama thanks for reviewing and merging!

**Pull request merged**
