### PR TITLE
Add basic scenario guide

### PR DESCRIPTION
**Pull request by felixfontein**
This adds a scenario guide which will be shown on the Ansible docsite (once this appears in a new Ansible release). A preview is available here: https://ansible.fontein.de/collections/community/sops/ (the guide itself is https://ansible.fontein.de/collections/community/sops/docsite/guide.html)

### CODE REVIEW

**Review by endorama — APPROVED** [review]
Very nice!!

**Comment by endorama** [comment]
@felixfontein how will the publishing of this doc works? Will it follow releases or `master`?

**Comment by felixfontein** [comment]
@endorama it follows releases. It's probably a good idea to release another patch release before the next Ansible 4 release (which will be in a bit less than two weeks).

**Comment by endorama** [comment]
@felixfontein Anything that we should to prepare for Ansible 4? Otherwise I'll go with the release by today.

**Comment by felixfontein** [comment]
I don't think so. Also Ansible 4.1.0 is already out, and the collection is working fine with it, so there's nothing to adjust for it.

**Comment by felixfontein** [comment]
@endorama thanks for reviewing this!

**Pull request merged**
