### PR TITLE
sops_encrypt: mark parameters containing secrets with no_log=True

### PR DESCRIPTION
**Pull request by felixfontein**
More fallout from ansible/ansible#73508.

We should release this as 1.0.4 ASAP.

### CODE REVIEW

**Review by tadeboro — APPROVED** [review]
Looks good. Not 100% sure why we should hide the threshold value, but that is probably because I do not know enough about crypto stuff.

**Comment by felixfontein** [comment]
@tadeboro the Shamir threshold value says how many keys are needed to decrypt a secret. That's part of the algorithm configuration, and definitely does not need to be secret. It's also stored directly in the metadata of an encrypted file (https://github.com/mozilla/sops/blob/develop/sops.go#L485).

**Comment by felixfontein** [comment]
Ah, sorry, I misread you. We don't hide it, I set `no_log=False` to explicitly mark it as "this is **not** secret", as https://github.com/ansible/ansible/pull/73508 will report it because of "secret" in the name :)

**Comment by felixfontein** [comment]
@tadeboro thanks for reviewing this!
@endorama I'll create a new release for this later today

**Comment by tadeboro** [comment]
Ugh, that was my bad. I did not notice that you are silencing the false positive.

**Pull request merged**
