### PR TITLE
vars plugin: make valid_extensions configurable

### LINKED ISSUE #183: Cant specify parameter: _valid_extensions in ansible.cfg
Hello :)

In my ansible inventory i encrypt only some of the variables with the command:
> sops —set ‘[“foo_password“] “password_value“‘ host_vars/example_host.yml

My .sops.yml looks like:
```
creation_rules:
  - age: <my-age-key>
     encrypted_regex: _(password|apikey)$
     mac_only_encrypted: true 
```

The encryption works fine and as expected, but the decryption is not working.
In ansible i use the community.sops.sops_vars-plugin and my ansible.cfg looks like:

```
[defaults]
vars_plugins_enabled = host_group_vars,community.sops.sops

[community.sops]
age_keyfile = <path to key-file>
config_file = <path to config-file>
_valid_extensions = [“.sops.yml“, “.sops.yaml“, “.sops.json“, “.yml“]
```

If i understood correctly i can say then community.sops.sops_vars-plugin with the parameter _valid_extensions that it should also read my normal yaml-files. But it does not work.

Thanks for your help, maybe i missunderstood something.

### PR DESCRIPTION
**Pull request by felixfontein**
### Motivation
See #183.

### Changes description
Makes the valid extensions configurable by the `valid_extensions` option in the `[community.sops]` section of ansible.cfg, or by the `ANSIBLE_VARS_SOPS_PLUGIN_VALID_EXTENSIONS` environment variable.

### Additional notes
Fixes #183.

### CODE REVIEW

**Comment by endorama** [comment]
I agree with this change but there is a caveat we need to double check. 

As this uses the generic vars file extension is it now possible for sops to run on non sops encrypted files. I remember choosing a separate extension on purpose, due to limitations on running sops on such files. I don't exactly remember if the issue was just with non sops encrypted files or with partially encrypted files too.

To ensure this functionality works as expected I think we need to add a couple of test to ensure that:
- it works as expected on partially encrypted files
- it works on non encrypted files

This would address being able to use just yaml/json extensions without unexpected failures.

What do you think? I may have a look during the next week.

**Comment by felixfontein** [comment]
As long as SOPS can decrypt the files, it will work.

It will definitely fail with non-encrypted files (sops will exit with `sops metadata not found`). (There's already a test for that, using the original extensions: `tests/integration/targets/vars_sops/test-bad-file/`.)

There's currently no way to test whether a file is sops-encrypted (I'm still waiting for https://github.com/getsops/sops/pull/545 to get rebased ;) ). It's probably best to add a warning that the plugin will not work if it applies to any file that's not sops-encrypted.

(Once that PR is merged and a new SOPS release is out I'd like to add some code that tests files before trying to decrypt them. There are quite a few things I'm planning to do once a new SOPS release is out. I really hope it happens soon...)

**Comment by felixfontein** [comment]
I improved the documentation accordingly (and while at it improved/removed some other things).

**Review by markuman — APPROVED** [review]

**Comment by felixfontein** [comment]
@endorama is the current version of the PR ok enough for you? If yes I'll merge it and create a new release so it can get included in tomorrow's Ansible releases.

**Comment by endorama** [comment]
> As long as SOPS can decrypt the files, it will work.
> It will definitely fail with non-encrypted files

@felixfontein It make sense and I think it's a good change anyway. It opens the door for shooting yourself in the foot but is also a useful feature for more advanced use cases and users.

> I'm still waiting for https://github.com/getsops/sops/pull/545 to get rebased ;)

🙏 Found some time to do it finally, it's now up to date.

> (Once that PR is merged and a new SOPS release is out I'd like to add some code that tests files before trying to decrypt them. There are quite a few things I'm planning to do once a new SOPS release is out. I really hope it happens soon...)

Looking forward to it!

**Review by endorama — APPROVED** [review]

**Comment by felixfontein** [comment]
@endorama @markuman thanks a lot for reviewing this!

**Comment by ZzenlD** [comment]
Is it now possible with the new filestatus in SOPS to encrypt only some of the inventory-files and the sops_vars plugin can automatically recognize if a "sops:"-part is present in the file or not? If not, it will skip the file without throwing an error.

This would allow a seamless integration into the ansible.

**Comment by felixfontein** [comment]
@ZzenlD check out the `handle_unencrypted_files` option (https://docs.ansible.com/ansible/devel/collections/community/sops/sops_vars.html#parameter-handle_unencrypted_files). You can set it to `skip`.

**Comment by ZzenlD** [comment]
Oh, my mistake... I really should read the documentation. Thanks for the implementation :)

**Pull request merged**
