### PR TITLE
Test with multiple sops versions, including the latest 3.7.0

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Comment by felixfontein** [comment]
Something went wrong with the 3.7.0 release, it seems to be broken.

**Comment by felixfontein** [comment]
Turns out the deb file contains a macOS executable. I filed mozilla/sops#839.

**Review by endorama — APPROVED** [review]

**Comment by felixfontein** [comment]
The issue has been fixed, I've restarted tests and they passed.

**Comment by felixfontein** [comment]
@endorama thanks for reviewing!

**Pull request merged**
