### PR TITLE
Improve coverage for var plugin tests

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by endorama** [comment]
@felixfontein thank you! The only thing I think is missing is how to add more test cases. I think I grasped the pattern (folder + `validate.sh`) but I struggle a bit understanding how that is expected to work. 

May you add some documentation about it? Or link any already existing docs about `vars` plugin testing.

**Comment by felixfontein** [comment]
I created a `README.md` explaining how the tests for the vars plugin work and how new tests can be added. I hope it's more clear now.

**Review by endorama — APPROVED** [review]

**Comment by endorama** [comment]
Perfect! Merging.

**Comment by felixfontein** [comment]
@endorama thanks for reviewing and merging!

**Pull request merged**
